In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [8]:
#OPTION 2



In [9]:
# Logistic Regression
lr = LogisticRegression(max_iter=10000)  # Increased max_iter to ensure convergence
lr.fit(X_train, y_train)
print("Logistic Regression Score:", lr.score(X_test, y_test))

Logistic Regression Score: 0.9611111111111111


In [10]:
# Support Vector Classifier (SVC)
svm = SVC()
svm.fit(X_train, y_train)
print("SVC Score:", svm.score(X_test, y_test))

SVC Score: 0.9851851851851852


In [7]:
# Optional: Random Forest Classifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
print("Random Forest Score:", rf.score(X_test, y_test))

Random Forest Score: 0.975925925925926


In [11]:
#OPTION 3 :- 1st method (lengthy) 



In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
#for example how kfold works !!!
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [21]:
#creating function get_score as a general model returns model_name.score takes model as the parameter !!
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [26]:
#StratifiedKFold  :- same as KFold ,, but little bit more advance and conveneient
from sklearn.model_selection import StratifiedKFold 
folds = StratifiedKFold(n_splits = 3)

In [30]:
scores_l =[]
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test,y_train, y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators =40), X_train, X_test, y_train, y_test))

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-

In [31]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [32]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
scores_rf

[0.9265442404006677, 0.9582637729549248, 0.9248747913188647]

In [34]:
#2nd method :- cross valid score :- best method 
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.90555556, 0.95821727, 0.96657382, 0.92200557])